apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic-system
spec:
  interval: 10m
  chart:
    spec:
      chart: eck-operator
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    managedNamespaces:
      - elastic
