apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  interval: 10m
  chart:
    spec:
      chart: elasticsearch
      version: 8.*
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: elasticsearch-values
      valuesKey: values.yaml
