apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  path: ./clusters/prod/longhorn   # ✅ peger på mappen med helmrelease/kustomization/namespace
  sourceRef:
    kind: GitRepository
    name: flux-system